### PR TITLE
fix: wait for initialize endpoint before updating client configs

### LINKED ISSUE #2499: handle impetulant client config changes
ToolHive doesn't immediately update clients when creating proxies and containers, but it is too quick for some clients leading to issues like https://github.com/stacklok/toolhive/issues/2271. There was a bit of investigation [here](https://github.com/StacklokLabs/mcp-optimizer/issues/51). Basically, initialise needs to be ready 0.1s after the cursor client is updated.

### Step 1: Container Deployment

- Calls runtime.Setup() to deploy the container
- For Kubernetes: Waits up to 2 minutes for the StatefulSet to become ready
- For Docker: Containers are created and started synchronously, but there's no explicit readiness check beyond Docker's API confirmation

### Step 2: Transport/Proxy Start

- Creates and starts the HTTP proxy server
- Only proceeds if this succeeds

### Step 3: Client Update

- ONLY AFTER both container deployment AND transport start succeed
- Calls clientManager.AddServerToClients() to update client configurations

To make this work we could get the proxy/toolhive to only update clients after it has called a successful initialise.

Alternatively, we could do the equivalent of a k8s health check and not set up the proxy until after it completes health checks. This does have the disadvantage or requiring MCP server to know about health checks. The other approach should work with any MCP server.

### PR DESCRIPTION
**Pull request by therealnb**
## Description

This PR ensures MCP servers are fully ready before notifying clients, preventing connection timing issues described in #2499.

## Changes

The proxy now:
1. Starts the container and proxy
2. **NEW:** Repeatedly calls the initialize endpoint until it succeeds (HTTP 200)
3. Waits up to 5 minutes with exponential backoff (100ms → 2s)
4. Only then updates client configurations

## Implementation Details

For streamable-http and SSE transports, the runner makes direct HTTP calls to the MCP initialize endpoint with proper headers:
- `Content-Type: application/json`
- `Accept: application/json, text/event-stream` (required by some MCP servers)
- `MCP-Protocol-Version: 2024-11-05`

The function uses exponential backoff to avoid hammering the server, with delays capped at 2 seconds between attempts and an overall timeout of 5 minutes for slow-starting servers like mcp-optimizer.

## Testing

- ✅ Builds successfully
- ✅ Linter passes (fixed all gosec, lll, and revive issues)
- ✅ Manually tested with mcp-optimizer (which requires ~30s to start)
- ✅ Backward compatible (continues with warning if initialize times out)

Fixes #2499, https://github.com/stacklok/toolhive/issues/2271

There is a video of this working [here](https://github.com/stacklok/toolhive/issues/2499#issuecomment-3503179985).

### CODE REVIEW

File: pkg/runner/runner.go [hunk 1]
```diff
@@ -450,3 +462,107 @@ func (r *Runner) Cleanup(ctx context.Context) error {
...
+		// For SSE/stdio, serverURL contains /sse#container-name
+		// Format: http://localhost:port/sse#container-name
+		// We need to change it to /messages (without the fragment)
+		endpoint = serverURL
+		// Remove fragment if present (everything after #)
+		if idx := strings.Index(endpoint, "#"); idx != -1 {
+			endpoint = endpoint[:idx]
+		}
+		// Replace /sse with /messages for the initialize call
+		endpoint = strings.Replace(endpoint, "/sse", "/messages", 1)
```
Comment (amirejaz) [inline pkg/runner/runner.go]: As I understand sse transport, the initialization call for the SSE transport occurs on the /sse endpoint and uses a GET request.

File: pkg/runner/runner.go [hunk 2]
```diff
@@ -274,21 +276,31 @@ func (r *Runner) Run(ctx context.Context) error {
...
+	serverURL := transport.GenerateMCPServerURL(
+		transportType,
+		"localhost",
+		r.Config.Port,
+		r.Config.ContainerName,
+		r.Config.RemoteURL)
+
+	// Repeatedly try calling initialize until it succeeds (up to 5 minutes)
+	// Some servers (like mcp-optimizer) can take significant time to start up
+	if err := waitForInitializeSuccess(ctx, serverURL, transportType, 5*time.Minute); err != nil {
```
Comment (tgrunnagle) [inline pkg/runner/runner.go]: noob question: will this block the `thv run` in the terminal while this is waiting?

File: pkg/runner/runner.go [hunk 3]
```diff
@@ -450,3 +462,119 @@ func (r *Runner) Cleanup(ctx context.Context) error {
...
+	baseDelay := 100 * time.Millisecond
+	maxDelay := 2 * time.Second // Cap at 2 seconds between retries
+
+	logger.Infof("Waiting for MCP server to be ready at %s (timeout: %v)", endpoint, maxWaitTime)
+
+	for {
+		attempt++
+
+		// Create a new HTTP client with a reasonable timeout for each request
+		httpClient := &http.Client{
```
Comment (tgrunnagle) [inline pkg/runner/runner.go]: question: is it at all more efficient to initialize the httpClient outside the loop?

File: pkg/runner/runner.go [hunk 4]
```diff
@@ -450,3 +462,119 @@ func (r *Runner) Cleanup(ctx context.Context) error {
...
+		// For other transports, no HTTP check is needed
+		logger.Debugf("Skipping readiness check for transport type: %s", transportType)
+		return nil
+	}
+
+	// Setup retry logic with exponential backoff
+	startTime := time.Now()
+	attempt := 0
+	baseDelay := 100 * time.Millisecond
+	maxDelay := 2 * time.Second // Cap at 2 seconds between retries
```
Comment (tgrunnagle) [inline pkg/runner/runner.go:514]: nitpick: tracking `delay` and multiplying by 2 on every loop would mean tracking one less variable and doing one less check on `exp > 10` (updating delay after `time.After`)

File: pkg/runner/runner.go (hunk 2 above)
Comment (therealnb) [reply pkg/runner/runner.go]: It doesn't seem to.

File: pkg/runner/runner.go (hunk 3 above)
Comment (therealnb) [reply pkg/runner/runner.go]: It is marginal, just a couple of allocations, but I'll fix it. Thanks.

File: pkg/runner/runner.go (hunk 4 above)
Comment (therealnb) [reply pkg/runner/runner.go:514]: ok - will fix this.

File: pkg/runner/runner.go (hunk 1 above)
Comment (therealnb) [reply pkg/runner/runner.go]: should be done

**Comment by eleftherias** [comment]
There is an issue with calling initialize for STDIO MCP servers multiple times. The behaviour is not determined by the spec so they may reject the request https://github.com/stacklok/toolhive/issues/1982. That's why ToolHive avoids calling initialize itself and only forwards the client request.

**Comment by therealnb** [comment]
Discussion [here](https://stacklok.slack.com/archives/C08JYS26TV3/p1762536169654909).

**Comment by therealnb** [comment]
@amirejaz , this should skip the stdio servers https://github.com/stacklok/toolhive/pull/2504/commits/1a1e44bedb6d9e6a122d9651a3bebada194862c5
