### PR TITLE
Gracefully Shutdown Foreground Server on Interrupt

### LINKED ISSUE #1855: Foreground MCP servers are not removed when cancelled
## Bug description
When running an MCP server with the `--foreground` flag, it's not properly cleaned up and the status is marked as `unhealthy`.

## Steps to reproduce
`thv run fetch --foreground`

Press cmd + C, or Ctrl + C

Run `thv list --all`

## Expected behavior
The `fetch` MCP server should be in the list.

## Actual behavior
The `fetch` MCP server shows up in the list as unhealthy.
fetch     ghcr.io/stackloklabs/gofetch/server:0.0.6   unhealthy   http://127.0.0.1:32670/mcp             32670   mcp         default   2025-09-12 10:31:55.996616 +0200 CEST

## Environment (if relevant)
- OS/version: macOS with Rancher desktop
- ToolHive version: Latest commit `fc1aedf831b6ce500956220de0a4f039463172df` on main and `v0.2.17`

## Additional context
Logs
```
10:31AM	INFO	MCP server ghcr.io/stackloklabs/gofetch/server:0.0.6 is verified successfully
10:31AM	INFO	Using target port: 60585
10:31AM	INFO	Saved run configuration for fetch-f
10:31AM	INFO	OIDC validation disabled, using local user authentication
10:31AM	INFO	Using local user authentication for user: eleftheria
10:31AM	INFO	Setting up streamable-http transport...
10:31AM	INFO	Deploying workload fetch-f from image ghcr.io/stackloklabs/gofetch/server:0.0.6...
10:31AM	INFO	Container created: fetch-f
10:31AM	INFO	Starting streamable-http transport for fetch-f...
10:31AM	INFO	Setting up transparent proxy to forward from host port 32670 to http://127.0.0.1:11936
10:31AM	INFO	Applied middleware 2
10:31AM	INFO	Applied middleware 1
10:31AM	INFO	HTTP transport started for fetch-f on port 32670
10:31AM	INFO	MCP server fetch-f started successfully
10:31AM	INFO	Server fetch-f belongs to group default, updating 1 registered client(s)
10:31AM	INFO	Updating client configuration: /Users/eleftheria/.cursor/mcp.json
10:31AM	INFO	Successfully updated the client config file for MCPServer fetch-f
10:31AM	INFO	Successfully updated client configuration: /Users/eleftheria/.cursor/mcp.json
10:31AM	INFO	Press Ctrl+C to stop or wait for container to exit
10:31AM	INFO	Detected initialize method call for fetch-f
10:31AM	ERROR	Failed to forward request: dial tcp 127.0.0.1:11936: connect: connection refused
2025/09/12 10:31:56 http: proxy error: dial tcp 127.0.0.1:11936: connect: connection refused
10:31AM	ERROR	Failed to forward request: dial tcp 127.0.0.1:11936: connect: connection refused
2025/09/12 10:31:56 http: proxy error: dial tcp 127.0.0.1:11936: connect: connection refused
10:32AM	INFO	MCP server not initialized yet, skipping health check for fetch-f
^C10:32AM	INFO	Received signal: interrupt, stopping server "fetch-f"
```

### PR DESCRIPTION
**Pull request by jerm-dro**
## Summary

This pull request is a second attempt at #2863: Gracefully shutting down foreground servers when receiving a SIGINT.

This PR takes greater care to fix tests which became flaky with the original change.

Fixes #1855.

### osv_mcp_server_test.go
This file has a test that became flaky, specifically the `Running OSV MCP server in the foreground"` tests. This is the only  e2e test that exercises the foreground server like a user would. I made the following changes to the test/code to ensure it passes:
- Update the test to document how SIGINT should behave rather than using `thv stop/rm`.
- Simplify the handling of context cancellation in `runForeground`. Previously, we had two goroutines doing parallel shutdown work: `workloadManager.RunWorkload` and `runForeground`. `runForeground` calls `RunWorkload` so it's natural to block within `runForeground` until `RunWorload` returns. Previously, the two shutdown routines could race on modifying/deleting the workload.

Screenshot 2025-12-07 at 3 32 00 PM

### fetch_mcp_server_test.go

This file and likely others exercise `--foreground` indirectly. The fetch tests are structured to stop a server with a shared name in between tests. Previously, `thv stop` sent a SIGINT to the background process `thv restart --foreground` that was spawned by `thv run`. When the background process received that signal, the signal handler we removed called `os.Exit` causing the process to exit and no longer babysit the workload. 

**The problem and solution** 

`thv restart` was intentionally coded to ignore context cancellation because we wanted a timeout around the restart's initial startup. Because `thv restart` ignore all context cancellation, it effectively ignored all SIGINTs and the process would continually resuscitate the server with stale state we were attempting to change across tests. The solution preserves the timeout on startup but ensures post-startup context cancellation is respected. 

Screenshot 2025-12-07 at 3 36 58 PM

This reverts commit 837e0f521f7ab5dca5a9407fb226c74852d402b4.

### CODE REVIEW

File: cmd/thv/main.go [hunk 1]
```diff
@@ -47,8 +48,10 @@ func main() {
 		migration.CheckAndPerformDefaultGroupMigration()
 	}
 
+	cmd := app.NewRootCmd(!app.IsCompletionCommand(os.Args) && !runtime.IsKubernetesRuntime())
```
Comment (dmjb) [inline cmd/thv/main.go]: Nitpick: The `IsKubernetesRuntime()` function will never return `true` since the operator always uses the `thv-proxyrunner` CLI. It should be safe to remove it, even if the code previously checked for it.

File: pkg/runner/runner.go [hunk 2]
```diff
@@ -317,16 +315,19 @@ func (r *Runner) Run(ctx context.Context) error {
 
 	// Define a function to stop the MCP server
 	stopMCPServer := func(reason string) {
+		// Use a background context to avoid cancellation of the main context.
+		cleanupCtx, cleanupCancel := context.WithTimeout(context.Background(), 10*time.Second)
```
Comment (dmjb) [inline pkg/runner/runner.go]: 10 seconds may not be long enough. Some MCP servers take some time to shut down, particularly when draining open connections. I'd pick 1 minute as a starting guess for this.

File: pkg/workloads/manager.go [hunk 3]
```diff
@@ -943,35 +943,36 @@ func (d *DefaultManager) updateSingleWorkload(workloadName string, newConfig *ru
...
 
 	// This is a container-based workload
-	return d.restartContainerWorkload(childCtx, name, foreground)
+	return d.restartContainerWorkload(ctx, name, foreground)
 }
 
 // restartRemoteWorkload handles restarting a remote workload
 func (d *DefaultManager) restartRemoteWorkload(
-	ctx context.Context,
+	timeoutLessCtx context.Context,
```
Comment (dmjb) [inline pkg/workloads/manager.go]: Nit: From what I have seen of Go codebases, it's more idiomatic to pass the context as `ctx`, then over-write the ctx variable, e.g.

`ctx, cancel := context.WithTimeout(ctx, AsyncOperationTimeout)`

File: cmd/thv/main.go (hunk 1 above)
Comment (jerm-dro) [reply cmd/thv/main.go]: Deleted.

File: pkg/runner/runner.go (hunk 2 above)
Comment (jerm-dro) [reply pkg/runner/runner.go]: Done.

File: pkg/workloads/manager.go (hunk 3 above)
Comment (jerm-dro) [reply pkg/workloads/manager.go]: That's true, but this is a case where we don't want totally follow convention. This code mixes code that should and should not be under timeout.

I'll make a slightly larger change that allows us to follow convention.

Comment (jerm-dro) [reply pkg/workloads/manager.go]: I ended up removing the old comments that explained why setup and start had different contexts. It seemed redundant with the improved factoring.
