### PR TITLE
Validate port range in oauth callback

### LINKED ISSUE #1983: Value of `--remote-auth-callback-port` is not validated
## Bug description

The `--remote-auth-callback-port` accepts invalid values. In this case, the behavior is that the hardcoded default port `8666` is used instead.

Seems it should be validated (1-65535, or 1024-65535 to avoid privileged port issues) and return an error to avoid unexpected/undefined behavior.

## Steps to reproduce

Run a remote MCP with an invalid callback port:

```
thv run notion-remote --remote-auth-callback-port 123456778
```

## Expected behavior

I'd expect an error about the invalid port number.

## Actual behavior

ToolHive doesn't indicate any error or warning, and initiates the dynamic client registration flow using the default `8666` callback port.

This works, but is unexpected.

## Environment (if relevant)
- ToolHive version: v0.3.5

## Additional context
Any additional information or logs you think might help.

### PR DESCRIPTION
**Pull request by eleftherias**
Add port range validation to the CLI and add missing port validation to API.

Fix #1983

### CODE REVIEW

File: pkg/networking/port.go [hunk 1]
```diff
@@ -142,15 +142,20 @@ func FindOrUsePort(port int) (int, error) {
...
+// It checks that the port is within the valid range (1-65535) and, for pre-registered
+// clients (with clientID), it returns an error if the port is not available.
 func ValidateCallbackPort(callbackPort int, clientID string) error {
 	// If port is 0, we'll find an available port later, so no need to validate
 	if callbackPort == 0 {
 		return nil
 	}
 
+	// Validate port range
+	if callbackPort < 1 || callbackPort > 65535 {
```
Comment (amirejaz) [inline pkg/networking/port.go]: According to the UI: `Port must be between 1024 and 65535`

Comment (amirejaz) [reply pkg/networking/port.go]: Screenshot 2025-11-21 at 15 00 26

Comment (eleftherias) [reply pkg/networking/port.go]: Thanks! Updated the code

**Review by amirejaz — APPROVED** [review]
