### PR TITLE
fix: automatically handle container exits and reconnect clients

### LINKED ISSUE #2270: Clients lose their connection
## Bug description
In cursor, have a tool registered. Restart the pod (or break the http connection in another way). The tool no longer works.

This also happens in cline in vscode. Disabling and re-enabling the tool fixes the problem.

## Steps to reproduce
See video

https://github.com/user-attachments/assets/e37b3cd9-2490-44e0-b3f0-b45fcc7a29d5

## Expected behavior
The tool should work, on a container restart.

## Actual behavior
It doesn't

## Environment (if relevant)
- OS/version: Mac 15.6.1
- ToolHive version: v0.3.7-14-g595e5e76-dirty

## Additional context
This is more a client problem than toolhive, but it will affect how toolhive is perceived and we can fix it. When a pod dies, we have to change the config (just touching the file doesn't work. we need to actually change the config)

### PR DESCRIPTION
**Pull request by therealnb**
Fixes #2270

## Problem

When containers exit or are removed, clients (Cursor, Cline, VSCode) lose connection and tools stop working. The issue noted: "When a pod dies, we have to change the config (just touching the file doesn't work. we need to actually change the config)"

## Solution

This PR implements automatic container exit handling with client config updates to force reconnection.

### Key Changes

**1. Automatic Container Exit Detection**
- Transport layer detects when containers exit or are removed
- Clear logging distinguishes between crash vs intentional removal
- Made `TransparentProxy.Stop()` idempotent to prevent panics

**2. Smart Workload Existence Check**
- Verifies container actually exists in Docker runtime (not just status files)
- Uses `thv ls` as source of truth for whether to restart or clean up

**3. Automatic Restart with Exponential Backoff**
- Retries: 5s → 10s → 20s → 40s → 60s (capped)
- Up to 10 attempts (~10 minutes total)
- Only retries actual container exits, not other errors

**4. Client Config Management (The Core Fix!)**
- **Before restart**: Removes server from `~/.cursor/mcp.json`
- **After restart**: Re-adds server to `~/.cursor/mcp.json`
- This forces clients to see the config change and reconnect with fresh sessions
- Solves the "we have to change the config" requirement from the issue

**5. Clean Removal Handling**
- If container removed (`docker rm`, `thv delete`): permanently removes from client config
- Tool vanishes from client as expected

## Behavior

**Container exits (crash)**:
```
Exit detected → Remove from ~/.cursor/mcp.json → Wait with backoff → 
Restart container → Re-add to mcp.json → Client reconnects ✅
```

**Container removed intentionally**:
```
Removal detected → Remove from ~/.cursor/mcp.json → Exit gracefully →
Tool vanishes from client ✅
```

## Files Changed

- `pkg/transport/http.go` - Container exit handling for HTTP transport
- `pkg/transport/stdio.go` - Container exit handling for stdio transport  
- `pkg/transport/proxy/transparent/transparent_proxy.go` - Idempotent Stop()
- `pkg/runner/runner.go` - Workload existence check and client config cleanup
- `pkg/workloads/manager.go` - Automatic restart with backoff + config refresh
- `docs/fixes/container-exit-handling.md` - Documentation (new)

## Testing

✅ Container kill → Automatic restart → Client reconnects  
✅ Container remove → Clean config removal → Tool vanishes  
✅ Multiple failures → Exponential backoff works  
✅ No panics on double-close

Tested with Cursor on macOS.

### CODE REVIEW

**Comment by therealnb** [comment]
This may be related to https://discord.com/channels/1184987096302239844/1439759480069034036/1440007583145394297

File: pkg/transport/http.go [hunk 1]
```diff
@@ -273,14 +278,42 @@ func (t *HTTPTransport) handleContainerExit(ctx context.Context) {
...
-		// Stop the transport when the container exits
+		// Store the exit error so runner can check if restart is needed
+		t.exitErrMutex.Lock()
+		t.containerExitErr = err
+		t.exitErrMutex.Unlock()
+
+		logger.Warnf("Container %s exited: %v", t.containerName, err)
+
+		// Check if container was removed (not just exited)
+		isRemoved := err != nil && strings.Contains(err.Error(), "may have been removed")
```
Comment (amirejaz) [inline pkg/transport/http.go]: I’m not sure this error check is fully reliable. What do you think about introducing a custom error type so we can check it by type rather than by value?

File: pkg/transport/http.go [hunk 2]
```diff
@@ -273,14 +278,42 @@ func (t *HTTPTransport) handleContainerExit(ctx context.Context) {
 	case <-ctx.Done():
 		return
 	case err := <-t.errorCh:
-		logger.Infof("Container %s exited: %v", t.containerName, err)
-		// Stop the transport when the container exits
+		// Store the exit error so runner can check if restart is needed
+		t.exitErrMutex.Lock()
+		t.containerExitErr = err
```
Comment (amirejaz) [inline pkg/transport/http.go:284]: Is this strictly needed to have the new `containerExitErr`, can check the `err` directly here?

File: pkg/runner/runner.go [hunk 3]
```diff
@@ -414,12 +416,97 @@ func (r *Runner) Run(ctx context.Context) error {
...
+	// Create a minimal implementation that checks via status manager
+	return &workloadExistenceChecker{statusManager: r.statusManager}
+}
+
+// workloadExistenceChecker is a minimal implementation to check if a workload exists
+type workloadExistenceChecker struct {
+	statusManager statuses.StatusManager
+}
+
+func (w *workloadExistenceChecker) DoesWorkloadExist(ctx context.Context, workloadName string) (bool, error) {
```
Comment (amirejaz) [inline pkg/runner/runner.go]: Can we define this function on `Runner` instead and avoid the `getWorkloadManager` and `workloadExistenceChecker`?

File: pkg/transport/http.go (hunk 1 above)
Comment (therealnb) [reply pkg/transport/http.go]: Actually, I noticed that when it went in. Good point.

Comment (therealnb) [reply pkg/transport/http.go]: **Changes:**
- Added `ErrContainerRemoved` error type in `/Users/nigel/code/toolhive/pkg/container/docker/errors.go`
- Updated the container monitor in `/Users/nigel/code/toolhive/pkg/container/docker/monitor.go` to return `ErrContainerRemoved` instead of `ErrContainerExited` when a container is not found
- Replaced string matching (`strings.Contains(err.Error(), "may have been removed")`) with typed error checking (`errors.Is(err, docker.ErrContainerRemoved)`) in:
  - `/Users/nigel/code/toolhive/pkg/transport/http.go` (handleContainerExit and ShouldRestart methods)
  - `/Users/nigel/code/toolhive/pkg/transport/stdio.go` (handleContainerExit and ShouldRestart methods)
- Updated tests to use the new typed error:
  - `/Users/nigel/code/toolhive/pkg/transport/http_test.go`
  - `/Users/nigel/code/toolhive/pkg/transport/stdio_test.go`

File: pkg/transport/http.go (hunk 2 above)
Comment (therealnb) [reply pkg/transport/http.go:284]: The `containerExitErr` field with mutex protection IS necessary because:
- The error comes from a channel in a goroutine (`handleContainerExit`)
- The `ShouldRestart()` method is called from a different context (from the workload manager)
- We need thread-safe access to the error to determine restart logic
- The field + mutex ensures safe concurrent access to the exit error state

Well, that's what the LLM said. Sounds plausible to me.

File: pkg/runner/runner.go (hunk 3 above)
Comment (therealnb) [reply pkg/runner/runner.go]: Seems like a good idea...
**Changes:**
- Moved `DoesWorkloadExist` method directly onto the `Runner` struct in `/Users/nigel/code/toolhive/pkg/runner/runner.go`
- Removed the `workloadExistenceChecker` type
- Removed the `getWorkloadManager` helper method
- Updated the call site to use `r.DoesWorkloadExist()` directly

File: pkg/runner/runner.go [hunk 4]
```diff
@@ -414,12 +416,86 @@ func (r *Runner) Run(ctx context.Context) error {
...
+		return fmt.Errorf("container exited, restart needed")
 	}
 
 	return nil
 }
 
+// DoesWorkloadExist checks if a workload exists in the status manager and runtime.
+// For remote workloads, it trusts the status manager.
+// For container workloads, it verifies the container exists in the runtime.
+func (r *Runner) DoesWorkloadExist(ctx context.Context, workloadName string) (bool, error) {
```
Comment (amirejaz) [inline pkg/runner/runner.go]: nit: lets make this private

**Review by amirejaz — APPROVED** [review]

File: pkg/runner/runner.go (hunk 4 above)
Comment (therealnb) [reply pkg/runner/runner.go]: ok - will do

Comment (therealnb) [reply pkg/runner/runner.go]: done
