### PR TITLE
Fix timeout handling for large Docker image pulls

### LINKED ISSUE #1665: API Timeout Issue with Large Docker Images
## Bug description

The API server uses a `Timeout` middleware with a **60-second timeout**:

```go
middleware.Timeout(middlewareTimeout), // middlewareTimeout = 60 * time.Second
```

This causes problems when downloading large Docker images (e.g., 1.25GB). When the download exceeds 60 seconds:

1. The HTTP request context gets cancelled
2. The Docker pull operation fails
3. Instead of a timeout-specific error, the system incorrectly reports:
   - **HTTP 500**: `"failed to retrieve server image: failed to retrieve or pull image: image not found in registry"`

The misleading error message masks the actual timeout issue, making debugging difficult. The error should indicate a timeout rather than suggesting the image doesn't exist in the registry.

It is connected to a UI issue raised [here](https://github.com/stacklok/toolhive-studio/issues/819#issuecomment-3242358295)

## Steps to reproduce
Download a large docker image with a poor connection

## Expected behavior
Explain what you expected to happen.

## Actual behavior
Explain what actually happened.

## Environment (if relevant)
- OS/version:
- ToolHive version:

## Additional context
Any additional information or logs you think might help.

### PR DESCRIPTION
**Pull request by JAORMX**
## Summary

This PR fixes the API timeout issue when pulling large Docker images (>1GB) by implementing a dedicated timeout context for image retrieval operations.

## Problem

Previously, when pulling large Docker images that took longer than the 60-second API timeout, the system would incorrectly report "image not found in registry" instead of indicating a timeout error. This misleading error message made debugging difficult.

## Solution

The fix introduces:
1. A dedicated 10-minute timeout context specifically for image retrieval operations
2. Proper detection of timeout errors using `context.DeadlineExceeded`
3. Clear, informative error messages when timeouts occur

## Changes

- Added `imageRetrievalTimeout` constant set to 10 minutes in `pkg/api/v1/workload_service.go`
- Created a dedicated context with longer timeout for image pulls
- Enhanced error handling in `pkg/runner/retriever/retriever.go` to check for `context.DeadlineExceeded` and `context.Canceled`
- Return clear timeout error messages instead of misleading "image not found" errors

## Testing

- ✅ All existing unit tests pass
- ✅ Linting passes (except for pre-existing cyclomatic complexity warning)
- The fix properly handles:
  - Large images that exceed the previous 60-second timeout
  - Context cancellation scenarios
  - Normal image pull operations

## Impact

This change improves the user experience by:
- Providing accurate error messages when image pulls timeout
- Allowing sufficient time for large image downloads
- Maintaining backward compatibility for normal operations

Fixes #1665

## Related Issues

This also addresses the UI issue mentioned in stacklok/toolhive-studio#819

### CODE REVIEW

File: pkg/api/v1/workload_service.go [hunk 1]
```diff
@@ -85,6 +92,7 @@ func (s *WorkloadService) UpdateWorkloadFromRequest(ctx context.Context, name st
 }
 
 // BuildFullRunConfig builds a complete RunConfig
+//nolint:gocyclo // TODO: refactor this into shorter functions
```
Comment (JAORMX) [inline pkg/api/v1/workload_service.go:96]: I added this as a TODO so I wouldn't bloat the PR with more changes. This can be handled separately.
