### PR TITLE
Fix group case insensitive

### LINKED ISSUE #1699: Group name is case-sensitive on Linux
## Bug description
Group names are designed to be case-insensitive, but they are case-sensitive on Linux.

## Steps to reproduce

On any Linux distribution, make the following request:

```bash
curl 'http://localhost:46381/api/v1beta/groups' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-US' \
  -H 'Connection: keep-alive' \
  -H 'Referer: http://localhost:5173/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) ToolHive/0.0.0-dev Chrome/138.0.7204.185 Electron/37.2.6 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'sec-ch-ua: "Not)A;Brand";v="8", "Chromium";v="138"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'x-client-platform: linux' \
  -H 'x-client-release-build: false' \
  -H 'x-client-type: toolhive-studio' \
  -H 'x-client-version: 0.0.0-dev' \
  --data-raw '{"name":"defAult"}'
```

this should fail, because the `default` group always exists. But on Linux, I am able to create a group called `defAult`

## Expected behavior
Error:

"group_already_exists: group 'defAult' already exists"

## Actual behavior

on Linux, I am able to create a group called `defAult`

## Environment (if relevant)
ToolHive v0.2.15
Commit: d274a0ac5468ed5af28b300282cc199a6473a415
Built: 2025-09-02 15:05:24 UTC
Go version: go1.24.1
Platform: linux/amd64

## Additional context

Seems like the problem is this:

```
On Linux/amd64 (so, standard Linux on x86-64), the behavior of os.Stat(filePath) is case-sensitive almost all the time.
```

### PR DESCRIPTION
**Pull request by rbiamru**
Fixes #1699

### What was happening
Group names were treated as case-sensitive on Linux. This allowed creating both `default` and `defAult` as separate groups, even though groups were intended to be case-insensitive.

### What I changed
- Added validation to enforce **lowercase-only** group names in `manager.go` (`Create`, `Get`, `Delete`, `Exists`).
- Group names with uppercase characters are now rejected with a clear error.
```
Error: invalid group name: "MyGroup" (must be lowercase)
```
- Updated unit tests in group_test.go:
 - Folded invalid-name tests into `TestManager_Create` (uppercase + mixed-case).
 -  Verified that duplicates with different casing are rejected at validation.
 -  Kept "success" and "already exists" cases intact.
   
### How I tested
- Built and ran locally on Windows with Docker (`nginx` workload).
-  Manual CLI tests:
   - `./thv group create MyGroup` → error
   - `./thv run --group MyGroup docker.io/library/nginx:latest` → error
   - `./thv group create mygroup` → success
Screenshot 2025-09-04 102242
  - Creating `defAult` since default.json already present in Local/toolhive/groups
Screenshot 2025-09-04 104234

- Unit tests pass:
Screenshot 2025-09-04 100917

### CODE REVIEW

File: pkg/groups/manager.go [hunk 1]
```diff
@@ -34,6 +34,8 @@ func NewManager() (Manager, error) {
 
 // Create creates a new group with the given name
 func (m *manager) Create(ctx context.Context, name string) error {
+	// Lowercase the group name before checking for existence
+	name = strings.ToLower(name)
```
Comment (blkt) [inline pkg/groups/manager.go]: **issue:** I don't think this is the right way of fixing this problem.

The way this is implemented, the user would think that he/she was able to create a group named `MyGroup` with a mix of uppercase and lowercase letters, while that's not the case. Since this is a user defined property and the user will refer to it from the CLI, it might be better to ensure that `name == strings.ToLower(name)` and return a specific error when that's not the case.

Note that this would apply to all routines, not just `Create`.

@amirejaz what do you think about it?

Comment (amirejaz) [reply pkg/groups/manager.go]: I agree @blkt , enforcing lowercase with a clear error across all routines makes sense.

Comment (rbiamru) [reply pkg/groups/manager.go]: Thanks for the feedback! I updated the implementation to enforce lowercase validation (no normalization) and updated tests to assert errors for uppercase & mixed-case names. Verified `group create` / `run --group`. Both CLI and unit tests now pass.

/cc @blkt @amirejaz

**Review by amirejaz — DISMISSED** [review]
Looks good to me!
Nit: There are a few extra new lines—would be great to remove them.

**Comment by rbiamru** [comment]
I’ve verified this locally with:
- `golangci-lint` → 0 issues
- `go test ./pkg/groups -v` → all tests passed

/cc @blkt @amirejaz

**Comment by rbiamru** [comment]
Thanks for the reviews and merge🙏
I appreciate the feedback and learned a lot from this change. 
Looking forward to contributing more!

**Comment by amirejaz** [comment]
> Thanks for the reviews and merge🙏 I appreciate the feedback and learned a lot from this change. Looking forward to contributing more!

Thanks a lot for your contribution @rbiamru , we really appreciate the effort! 🙌
If you’re interested in contributing more, you can check out our [good first issues](https://github.com/stacklok/toolhive/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22good%20first%20issue%22), or explore any of the other open issues in the repo. We’d love to see more of your contributions! 🚀
