### PR TITLE
Gracefully Shutdown Foreground Server on Interrupt

### LINKED ISSUE #1855: Foreground MCP servers are not removed when cancelled
## Bug description
When running an MCP server with the `--foreground` flag, it's not properly cleaned up and the status is marked as `unhealthy`.

## Steps to reproduce
`thv run fetch --foreground`

Press cmd + C, or Ctrl + C

Run `thv list --all`

## Expected behavior
The `fetch` MCP server should be in the list.

## Actual behavior
The `fetch` MCP server shows up in the list as unhealthy.
fetch     ghcr.io/stackloklabs/gofetch/server:0.0.6   unhealthy   http://127.0.0.1:32670/mcp             32670   mcp         default   2025-09-12 10:31:55.996616 +0200 CEST

## Environment (if relevant)
- OS/version: macOS with Rancher desktop
- ToolHive version: Latest commit `fc1aedf831b6ce500956220de0a4f039463172df` on main and `v0.2.17`

## Additional context
Logs
```
10:31AM	INFO	MCP server ghcr.io/stackloklabs/gofetch/server:0.0.6 is verified successfully
10:31AM	INFO	Using target port: 60585
10:31AM	INFO	Saved run configuration for fetch-f
10:31AM	INFO	OIDC validation disabled, using local user authentication
10:31AM	INFO	Using local user authentication for user: eleftheria
10:31AM	INFO	Setting up streamable-http transport...
10:31AM	INFO	Deploying workload fetch-f from image ghcr.io/stackloklabs/gofetch/server:0.0.6...
10:31AM	INFO	Container created: fetch-f
10:31AM	INFO	Starting streamable-http transport for fetch-f...
10:31AM	INFO	Setting up transparent proxy to forward from host port 32670 to http://127.0.0.1:11936
10:31AM	INFO	Applied middleware 2
10:31AM	INFO	Applied middleware 1
10:31AM	INFO	HTTP transport started for fetch-f on port 32670
10:31AM	INFO	MCP server fetch-f started successfully
10:31AM	INFO	Server fetch-f belongs to group default, updating 1 registered client(s)
10:31AM	INFO	Updating client configuration: /Users/eleftheria/.cursor/mcp.json
10:31AM	INFO	Successfully updated the client config file for MCPServer fetch-f
10:31AM	INFO	Successfully updated client configuration: /Users/eleftheria/.cursor/mcp.json
10:31AM	INFO	Press Ctrl+C to stop or wait for container to exit
10:31AM	INFO	Detected initialize method call for fetch-f
10:31AM	ERROR	Failed to forward request: dial tcp 127.0.0.1:11936: connect: connection refused
2025/09/12 10:31:56 http: proxy error: dial tcp 127.0.0.1:11936: connect: connection refused
10:31AM	ERROR	Failed to forward request: dial tcp 127.0.0.1:11936: connect: connection refused
2025/09/12 10:31:56 http: proxy error: dial tcp 127.0.0.1:11936: connect: connection refused
10:32AM	INFO	MCP server not initialized yet, skipping health check for fetch-f
^C10:32AM	INFO	Received signal: interrupt, stopping server "fetch-f"
```

### PR DESCRIPTION
**Pull request by jerm-dro**
## Summary

Fix interrupting of `thv run --foreground` so it completely removes the server after interrupt.

Fixes #1855

The expected behavior described in the issue is to have the server still appear in the `thv list --all` results with a status other than `unhealthy`. The existing shutdown code that is now successfully running fully deletes the workload. As a separate enhancement, the shutdown code could be changed to leave the workload in a stopped state.

## Problem

The root problem here was two competing `signal.Notify` handlers. One is registered by `runner.Run` to stop the server. The other, I’ll call the default handler, is registered in `setupSignalHandle` in `cmd/thv/main.go` (seen [here](https://github.com/stacklok/toolhive/blob/main/cmd/thv/main.go#L62-L72)). 

Both of these signal handlers are notified upon interrupt. The default handler calls `os.Exit(0)` fairly quickly, which results in the `run` signal handler to not run to completion. This leaves a status file with a `running` status for the associated workload. 

When running `thv list --all` , we detect there is no container but the status file claims it is running. Upon detection of this discrepancy, `thv` updates the status of the workload to `unhealthy`.

## Solution

The solution here avoids the competing signal handlers by:

- Removing the `os.Exit(0)` from the default handler.
- When the default handler receives a signal, cancel the context that is plumbed to the run command.
- Remove the run signal handler and instead rely on context cancellation.

**This solution is not without risk**: Commands that don’t check for context cancellation and relied on the `os.Exit(0)` may now continue running until they hit code that does respect the context cancellation. Based on my understanding of the code, `thv run --foreground` is one of the few commands that can be long running, so I think this risk is relatively small.

Beyond the scope of this pull request, I think we should prefer to rely on context cancellation rather than using `signal.Notify` deep in the implementation of commands. This “competing signal handlers” problem likely exists elsewhere: I count 10 uses of `signal.Notify`. 

## Alternatives Considered

- Don’t `os.Exit(0)` in the default handler and let both run to completion. This results in a normal exit for `thv run`  since `runner.Run` will return once its signal handler complete. However, other commands may rely on `os.Exit(0)` for proper exiting.
- Call `signal.Reset` before registering `runner.Run`'s signal handler. We could imitate the behavior of the default signal handler within the run signal handler, but this seems less maintainable and adds unnecessary complexity to run. Run should not concern itself with what needs to happen on all cancellations nor why exactly it’s being cancelled.
- Solve the problem on `thv list --all` side. A solution could be implemented here, but it doesn’t address the root of the problem: not completing the graceful shutdown. If we don’t address the root, I can imagine this causes future bugs.

## Testing

I manually tested the fix:
Screenshot 2025-12-02 at 4 13 27 PM

### CODE REVIEW

File: pkg/runner/runner.go [hunk 1]
```diff
@@ -330,15 +330,6 @@ func (r *Runner) Run(ctx context.Context) error {
...
 		}
 
-		// Remove the PID file if it exists
-		// TODO: Stop writing to PID file once we migrate over to statuses.
-		if err := process.RemovePIDFile(r.Config.BaseName); err != nil {
-			logger.Warnf("Warning: Failed to remove PID file: %v", err)
-		}
-		if err := r.statusManager.ResetWorkloadPID(ctx, r.Config.BaseName); err != nil {
-			logger.Warnf("Warning: Failed to reset workload %s PID: %v", r.Config.ContainerName, err)
-		}
```
Comment (jerm-dro) [inline pkg/runner/runner.go:340]: I removed this since it was always producing error logs.

File: pkg/runner/runner.go [hunk 2]
```diff
@@ -403,8 +394,8 @@ func (r *Runner) Run(ctx context.Context) error {
 
 	// Wait for either a signal or the done channel to be closed
 	select {
-	case sig := <-sigCh:
```
Comment (jhrozek) [inline pkg/runner/runner.go:406]: can we now remove sigCh in runner go? (Is it superseded by ctx's signal handling) ?

File: pkg/runner/runner.go [hunk 3]
```diff
@@ -330,15 +330,6 @@ func (r *Runner) Run(ctx context.Context) error {
 			logger.Warnf("Warning: Failed to cleanup telemetry: %v", err)
 		}
 
-		// Remove the PID file if it exists
-		// TODO: Stop writing to PID file once we migrate over to statuses.
-		if err := process.RemovePIDFile(r.Config.BaseName); err != nil {
```
Comment (jhrozek) [inline pkg/runner/runner.go:335]: Does this mean we leave stale PID files on the disk on Ctrl+C ?

**Review by jhrozek — COMMENTED** [review]
I like the simplification but I'm not sure I understand all the edge cases. Two comments added, but I think e.g. @dmjb is better suited to review this PR

File: pkg/runner/runner.go (hunk 3 above)
Comment (dmjb) [reply pkg/runner/runner.go:335]: IIRC, we are still creating the PID file in the current version of ToolHive. To get rid of them fully, we need a two step process:

1) Get rid of the WritePIDFile function, and all code which uses it.
2) At some point, once we are happy that all the PID file creating versions of ToolHive are out of use, get rid of the cleanup code too.

As part of that change, we should change any warning logging around pid file cleanup to debug level instead. This is because we now expect that pid files will not get created.

File: pkg/runner/runner.go (hunk 2 above)
Comment (jerm-dro) [reply pkg/runner/runner.go:406]: Yes, thanks for catching that.

File: pkg/runner/runner.go (hunk 3 above)
Comment (jerm-dro) [reply pkg/runner/runner.go:335]: I've reverted the deletion of this code for now.

**Review by dmjb — APPROVED** [review]
