### PR TITLE
fix: prevent zombie supervisor processes on restart

### LINKED ISSUE #2274: zombie issues
## Bug description
See the sequence of commands below. There seem to be accidental long lived process for thv.

## Steps to reproduce
```
nigels-MacBook-Pro:code nigel$ ps aux | grep 'thv'
nigel            48437   0.3  0.1 411547648  16608   ??  Ss   11:17a.m.   0:03.11 /Users/nigel/go/bin/thv restart github --foreground
nigel            56254   0.0  0.3 411530208  50256   ??  Ss   12:29p.m.   0:00.65 /Users/nigel/go/bin/thv restart meta-mcp --foreground
nigel            53714   0.0  0.2 412040784  39824 s006  S+   12:12p.m.   0:00.71 /Users/nigel/code/toolhive-studio/bin/darwin-arm64/thv serve --openapi --experimental-mcp --experimental-mcp-host=127.0.0.1 --experimental-mcp-port=60887 --host=127.0.0.1 --port=50065
nigel            47643   0.0  0.1 411554992  18832   ??  Ss   10:35a.m.   0:05.46 /Users/nigel/go/bin/thv restart fetch --foreground
nigel            15761   0.0  0.0 411542112   4848   ??  S     5:14p.m.   0:06.39 thv proxy stdio mcpserver-proxy-stdio-target-15280-1760976842757344000-1760976427
nigel            57598   0.0  0.0 410733664   1568 s019  S+   12:45p.m.   0:00.01 grep thv
nigels-MacBook-Pro:code nigel$ thv restart fetch
A new version of ToolHive is available: v0.3.11
Currently running: v0.3.7-14-g595e5e76-dirty
12:46PM	INFO	Container fetch is already running
Workload fetch restarted successfully
nigels-MacBook-Pro:code nigel$ ps aux | grep 'thv'
nigel            56254   0.0  0.3 411530208  43488   ??  Ss   12:29p.m.   0:00.69 /Users/nigel/go/bin/thv restart meta-mcp --foreground
nigel            53714   0.0  0.2 412032592  39776 s006  S+   12:12p.m.   0:00.75 /Users/nigel/code/toolhive-studio/bin/darwin-arm64/thv serve --openapi --experimental-mcp --experimental-mcp-host=127.0.0.1 --experimental-mcp-port=60887 --host=127.0.0.1 --port=50065
nigel            48437   0.0  0.1 411547904  23424   ??  Ss   11:17a.m.   0:03.16 /Users/nigel/go/bin/thv restart github --foreground
nigel            47643   0.0  0.2 411554992  25168   ??  Ss   10:35a.m.   0:05.52 /Users/nigel/go/bin/thv restart fetch --foreground
nigel            15761   0.0  0.0 411542112   4832   ??  S     5:14p.m.   0:06.41 thv proxy stdio mcpserver-proxy-stdio-target-15280-1760976842757344000-1760976427
nigel            57852   0.0  0.0 410734688   1664 s019  S+   12:46p.m.   0:00.00 grep thv
nigels-MacBook-Pro:code nigel$ thv stop fetch
A new version of ToolHive is available: v0.3.11
Currently running: v0.3.7-14-g595e5e76-dirty
12:48PM	INFO	Stopping proxy process (PID: 47643)...
12:48PM	INFO	Proxy process stopped
12:48PM	INFO	Stopping containers for fetch...
12:48PM	INFO	Server fetch belongs to group default, updating 0 registered client(s)
12:48PM	INFO	No target clients found for server fetch
12:48PM	INFO	Client configurations for fetch removed
12:48PM	INFO	Successfully stopped fetch...
workload fetch stopped successfully
nigels-MacBook-Pro:code nigel$ ps aux | grep 'thv'
nigel            56254   0.0  0.3 411530208  43280   ??  Ss   12:29p.m.   0:00.78 /Users/nigel/go/bin/thv restart meta-mcp --foreground
nigel            53714   0.0  0.1 412032592  18592 s006  S+   12:12p.m.   0:00.80 /Users/nigel/code/toolhive-studio/bin/darwin-arm64/thv serve --openapi --experimental-mcp --experimental-mcp-host=127.0.0.1 --experimental-mcp-port=60887 --host=127.0.0.1 --port=50065
nigel            48437   0.0  0.1 411547904  22976   ??  Ss   11:17a.m.   0:03.23 /Users/nigel/go/bin/thv restart github --foreground
nigel            15761   0.0  0.1 411542112  15120   ??  S     5:14p.m.   0:06.42 thv proxy stdio mcpserver-proxy-stdio-target-15280-1760976842757344000-1760976427
nigel            57903   0.0  0.0 410584080    736 s019  R+   12:48p.m.   0:00.01 grep thv
nigels-MacBook-Pro:code nigel$ thv restart fetch
A new version of ToolHive is available: v0.3.11
Currently running: v0.3.7-14-g595e5e76-dirty
12:49PM	INFO	Loaded configuration from state for fetch
12:49PM	INFO	Starting tooling server fetch...
12:49PM	INFO	Logging to: /Users/nigel/Library/Application Support/toolhive/logs/fetch.log
12:49PM	INFO	MCP server is running in the background (PID: 57975)
12:49PM	INFO	Use 'thv stop fetch' to stop the server
Workload fetch restarted successfully
nigels-MacBook-Pro:code nigel$ ps aux | grep 'thv'
nigel            56254   0.0  0.3 411530208  50432   ??  Ss   12:29p.m.   0:00.82 /Users/nigel/go/bin/thv restart meta-mcp --foreground
nigel            53714   0.0  0.1 412032592  18768 s006  S+   12:12p.m.   0:00.80 /Users/nigel/code/toolhive-studio/bin/darwin-arm64/thv serve --openapi --experimental-mcp --experimental-mcp-host=127.0.0.1 --experimental-mcp-port=60887 --host=127.0.0.1 --port=50065
nigel            48437   0.0  0.1 411547904  22592   ??  Ss   11:17a.m.   0:03.25 /Users/nigel/go/bin/thv restart github --foreground
nigel            15761   0.0  0.0 411542112   4848   ??  S     5:14p.m.   0:06.42 thv proxy stdio mcpserver-proxy-stdio-target-15280-1760976842757344000-1760976427
nigel            57985   0.0  0.0 410734688   1632 s019  S+   12:49p.m.   0:00.01 grep thv
nigel            57975   0.0  0.3 412049360  51760   ??  Ss   12:49p.m.   0:00.04 /Users/nigel/go/bin/thv restart fetch --foreground
```

## Expected behavior
No zombies

## Actual behavior
Zombies

## Environment (if relevant)
- OS/version: Mac 15.6.1
- ToolHive version: v0.3.7-14-g595e5e76-dirty

## Additional context
These probably don't do that much harm. The don't look good though.

### PR DESCRIPTION
**Pull request by therealnb**
## Description

Fixes #2274 and #2305 (as [tested](https://stacklok.slack.com/archives/C08JYS26TV3/p1761245971490159?thread_ts=1761211066.612429&cid=C08JYS26TV3) by @danbarr )

When running `thv restart` on an already-running workload, the command would return early with "Container is already running" but would NOT stop the old supervisor process. This caused supervisor processes to accumulate over time, leading to "zombie" processes.

## Root Cause

The `restartContainerWorkload` and `restartRemoteWorkload` functions had early return logic when the workload status was already "running":

```go
if err == nil && workload.Status == rt.WorkloadStatusRunning {
    logger.Infof("Container %s is already running", containerName)
    return nil  // ❌ Early return - supervisor process not stopped!
}
```

This meant:
- The old supervisor process (`thv restart <name> --foreground`) was never killed
- A new supervisor process was never started
- Multiple restart calls would leave multiple orphaned supervisor processes

## Solution

The fix ensures `restart` always performs a proper **stop→start cycle** when the workload is already running:

1. **Stop old supervisor** (kills the proxy process that manages HTTP/SSE translation)
2. **Stop container** if it's running
3. **Clean up** client configurations
4. **Start fresh** supervisor + container

### Key Changes

- `restartContainerWorkload` now checks if workload is running and stops it first
- `restartRemoteWorkload` applies the same logic for remote workloads
- Handles edge cases: dead supervisor, dead container, or both
- System is resilient - `stopProcess` gracefully handles missing PIDs

## Testing

✅ All unit tests pass (24/24)
✅ Added new unit test: `TestDefaultManager_restartLogicConsistency` verifies stop logic is called
✅ Added E2E test: `test/e2e/restart_zombie_test.go` verifies no process accumulation
✅ Linting passes (0 issues)

## Recovery Scenarios

The fix handles all failure scenarios:

| Scenario | Recovery |
|----------|----------|
| Supervisor killed, container running | ✅ Detects running container, gracefully handles missing PID, stops container, starts fresh |
| Container killed, supervisor running | ✅ Supervisor auto-exits when container dies, restart starts fresh |
| Both killed | ✅ No cleanup needed, directly starts fresh |
| Normal restart | ✅ Our fix! Stops both cleanly, starts fresh |

## Breaking Changes

None - this is a bug fix that makes `restart` behave as expected.

## Checklist

- [x] Code changes
- [x] Unit tests added/updated
- [x] E2E tests added
- [x] Linting passes
- [x] All tests pass
- [x] Documentation (excluded from commit per instructions)

### CODE REVIEW

**Comment by JAORMX** [comment]
@claude can you review this and ensure we don't have any regressions?

**Review by amirejaz — CHANGES_REQUESTED** [review]
My understanding is if the workload is already running whether it is local or remote, we should not let it restart. For the restart to work properly, it is required the workload to be stopped first using UI or `thv stop`.

@JAORMX pelase correct me if I'm wrong.

**Comment by therealnb** [comment]
@amirejaz , you are correct and we can probably fix some of the error without restarting each time.
@danbarr had said that the new behaviour was preferred (there were issues previously reported).

We need to decide how we want it to work.

Previously, stop and restart were broken, only rm worked.

**Comment by danbarr** [comment]
This is an "IMHO" thing; I know it was discussed quite some time ago, but to me "restart" should mean...restart. Not "repair", or "restart but only if you think something's wrong"?

I feel like this aligns better with user expectations of what a "restart" means, also lines up with the behavior of the same command in docker/podman CLIs (which the thv cli is largely modeled after).

But also understand that it was decided back then to keep it the way it was, and there might be knock-on effects to changing it.

**Comment by JAORMX** [comment]
@danbarr yeah, we should fix restart to actually restart. But that involves reworking the codebase with that assumption and making sure we don't break existing functionality. Which is a lot more involved.

**Comment by therealnb** [comment]
@amirejaz the code I have checked in is much more like the original behaviour, except with the bugs fixed. I have tested locally

### **Behavior Comparison:**

| State | Old (Broken) | PR Original | New (Fixed) |
|-------|-------------|-------------|-------------|
| Healthy + `restart` | No-op ✅ | Always restart ❌ | **No-op ✅** |
| Damaged + `restart` | No-op (zombie!) ❌ | Always restart ✅ | **Cleanup + restart ✅** |
| Stopped + `restart` | Start ✅ | Start ✅ | **Start ✅** |

Thanks for being diligent!

File: pkg/workloads/manager.go [hunk 1]
```diff
@@ -812,10 +834,33 @@ func (d *defaultManager) restartRemoteWorkload(
...
+		}
+
+		// Stop the supervisor process (proxy) if it exists (may already be dead)
+		// This ensures we clean up any orphaned supervisor processes
+		d.stopProxyIfNeeded(ctx, name, runConfig.BaseName)
+
+		// Clean up client configurations
+		if err := removeClientConfigurations(name, false); err != nil {
+			logger.Warnf("Warning: Failed to remove client configurations: %v", err)
+		}
```
Comment (amirejaz) [inline pkg/workloads/manager.go:863]: Should we set the state to `stopped`?

File: pkg/workloads/manager.go [hunk 2]
```diff
@@ -864,10 +911,62 @@ func (d *defaultManager) restartContainerWorkload(ctx context.Context, name stri
...
+				}
+				return fmt.Errorf("failed to stop container %s: %v", containerName, err)
+			}
+			logger.Infof("Container %s stopped", containerName)
+		}
+
+		// Clean up client configurations
+		if err := removeClientConfigurations(workloadName, labels.IsAuxiliaryWorkload(container.Labels)); err != nil {
+			logger.Warnf("Warning: Failed to remove client configurations: %v", err)
+		}
```
Comment (amirejaz) [inline pkg/workloads/manager.go:974]: should we set the status to `stopped`

Comment (therealnb) [reply pkg/workloads/manager.go:974]: claude agreed!
