### PR TITLE
Fix SSE connection timeout using background context for workload startup

### LINKED ISSUE #1572: MCP Client Cannot Connect to ToolHive SSE Endpoints after some time
### **Environment**
- **Claude Code Version:** 1.0.90
- **ToolHive Version:** v0.2.11  
- **OS:** macOS (darwin 24.5.0)

### **Issue Description**
Claude Code's MCP client consistently reports "Failed to connect" for all ToolHive-managed MCP servers during health checks, despite the servers running correctly and being accessible via direct HTTP requests. I also noticed this issue with Cursor.

### **Steps to Reproduce**
1. Start MCP servers via ToolHive: `thv run atlassian` 
2. Verify servers are running: `thv list`
3. Check Claude MCP status: `claude mcp list`

### **Expected Behavior**
Claude should successfully connect to the SSE endpoints and show servers as healthy.

### **Actual Behavior**
After some time interacting with claude code
```bash
$ claude mcp list
Checking MCP server health...

atlassian: http://localhost:39692/sse#atlassian (SSE) - ✗ Failed to connect
gitlab: http://localhost:17545/sse#gitlab (SSE) - ✗ Failed to connect
```

### **Evidence That MCP Servers Are Working Correctly**

**1. ToolHive shows servers running:**
```bash
$ thv list
NAME        PACKAGE                                    STATUS    URL                              PORT
atlassian   ghcr.io/sooperset/mcp-atlassian:latest    running   http://127.0.0.1:39692/sse#atlassian   39692
gitlab      toolhivelocal/npx-zereight-mcp-gitlab:*   running   http://127.0.0.1:17545/sse#gitlab      17545
```

**2. Direct SSE endpoint connectivity works:**
```bash
$ curl -v http://localhost:39692/sse
< HTTP/1.1 200 OK
< Content-Type: text/event-stream
< Cache-Control: no-cache
< Connection: keep-alive

event: endpoint
data: http://localhost:39692/messages?session_id=d366e107-ea88-499f-ae2a-268e4c70d946

: keep-alive
```

**3. Port binding is correct:**
```bash
$ lsof -i :39692
COMMAND   PID            USER   FD   TYPE   NODE NAME
thv     92132 mauriciobonetti    9u  IPv4    TCP localhost:39692 (LISTEN)
```

**4. MCP server logs show successful JSON-RPC communication:**
```
2:25PM  INFO    Received JSON-RPC message: *jsonrpc2.Request
2:25PM  INFO    JSON-RPC raw: {"jsonrpc":"2.0","id":4,"result":{"content":[...],"isError":false}}
2:25PM  INFO    Sanitized JSON: {"jsonrpc":"2.0","id":4,"result":{...}}
```

### **Evidence of Client-Proxy Communication Issue**

**1. Claude MCP configuration is correct:**
```json
// ~/.cursor/mcp.json
{
  "mcpServers": {
    "atlassian": {"url": "http://localhost:39692/sse#atlassian", "type": "sse"},
    "gitlab": {"url": "http://localhost:17545/sse#gitlab", "type": "sse"}
  }
}
```

**2. Proxy logs show frequent client disconnections:**
```
2:35PM  INFO    Client ce9f1eea-da39-4770-8f29-527b3a8ff609 disconnected
2:36PM  INFO    Client 51930f7b-825d-453f-84de-b2144d7a35cf disconnected
2:38PM  INFO    Client 169a7308-789a-4adf-a188-7cb81d86fa7d disconnected
[... many more disconnections ...]
```

**3. Manual SSE connection with Claude-like headers works:**
```bash
$ curl -H "Accept: text/event-stream" -H "User-Agent: Claude-Code" http://localhost:39692/sse
event: endpoint
data: http://localhost:39692/messages?session_id=d366e107-ea88-499f-ae2a-268e4c70d946
: keep-alive
```

### **Root Cause Analysis**
The issue appears to be a **communication problem between Claude Code client and the ToolHive proxy**, not with the MCP servers themselves. * - proxy logs show many short-lived connections

### **Attempted Solutions**
- Users reverted to version `v.0.2.9`, and the problem was no longer observed.

### PR DESCRIPTION
**Pull request by lujunsan**
## Summary
  Fixes SSE MCP connections timing out after exactly 5 minutes by ensuring restarted workloads (both container and remote) use a background context instead of inheriting the async operation timeout.

  ## Problem
  When restarting SSE workloads, both `restartContainerWorkload()` and `restartRemoteWorkload()` were passing a context with `AsyncOperationTimeout` (5 minutes) down to the actual workload execution. This caused SSE connections to be cancelled after exactly 5 minutes when the timeout context expired.

  ## Solution
  - Modified both `restartContainerWorkload()` and `restartRemoteWorkload()` to use `context.Background()` when starting workloads
  - Added clear comments explaining the context separation: setup operations use the timeout context, but the running workload needs an indefinite context
  - The `AsyncOperationTimeout` is now correctly scoped to only affect restart setup operations (loading state, stopping old containers) not the running workload itself

  ## Test plan
  - [x] Verified SSE connections no longer timeout after 5 minutes for both container and remote workloads
  - [x] Confirmed restart operations still timeout appropriately for setup steps
  - [x] Tested with reduced timeout (10 seconds) to confirm the fix

Fixes #1572

### CODE REVIEW

**Review by yrobla — APPROVED** [review]

File: pkg/workloads/manager.go [hunk 1]
```diff
@@ -695,8 +695,10 @@ func (d *defaultManager) restartContainerWorkload(childCtx context.Context, name
 		return err
 	}
 
-	// Start the workload
-	return d.startWorkload(childCtx, name, mcpRunner, foreground)
+	// Start the workload with background context to avoid timeout cancellation
+	// The childCtx with AsyncOperationTimeout is only for the restart setup operations,
+	// but the actual workload should run indefinitely with its own lifecycle management
```
Comment (eleftherias) [inline pkg/workloads/manager.go:701]: I believe the same change is needed for `restartContainerWorkload`.

File: pkg/workloads/manager.go [hunk 2]
```diff
@@ -695,8 +695,10 @@ func (d *defaultManager) restartContainerWorkload(childCtx context.Context, name
...
+	return d.startWorkload(context.Background(), name, mcpRunner, foreground)
```
Comment (eleftherias) [inline pkg/workloads/manager.go:702]: I was thinking the caller should also pass in the parent context, so that we can cancel it for foreground processes.
Something like:
```
	var workloadCtx context.Context
	if foreground {
		// Allow cancellation via Ctrl+C
		workloadCtx = parentCtx
	} else {
		// Isolate from HTTP request context to avoid timeout issues with proxy connections
		workloadCtx = context.Background()
	}
```

File: pkg/workloads/manager.go (hunk 1 above)
Comment (lujunsan) [reply pkg/workloads/manager.go:701]: Not sure I understand; `restartContainerWorkload` ultimately calls `startWorkload`, do you think there's anything called before `startWorkload` that should have it's own context?

Comment (eleftherias) [reply pkg/workloads/manager.go:701]: Sorry I meant `restartRemoteWorkload`

Comment (lujunsan) [reply pkg/workloads/manager.go:701]: Oh you are 100% right, we'd have the same issue there. Great catch! I'll include it in this PR

**Review by JAORMX — APPROVED** [review]
