### PR TITLE
Fix parsing middleware to handle SSE streams with any path

### LINKED ISSUE #1187: Parsing middleware fails on SSE streams
## Bug description
The Parsing middleware does not work correctly when the path does not contain `/messages`, `/message`, or `/mcp` (see [here](https://github.com/stacklok/toolhive/blob/main/pkg/mcp/parser.go#L114-L122)).

The problem is that the MCP spec allows for other endpoints to be used, as long as
* it's a single one for Streamable HTTP transport
* they're two distinct ones for SSE transport

In such cases, the parser skips parsing and forwards the request as is, which causes failures downstream (i.e. in the Authorization middleware).

## Steps to reproduce
I could only verify it using `dlv` and `curl`. See [here](https://github.com/StacklokLabs/gofetch/blob/main/USAGE.md#sse) for some example steps, but bear in mind that, when using SSE transport, `StacklokLabs/gofetch` MCP server relies on a single endpoint, namely `/sse`, for both SSE stream and messages, which is not conformant to the MCP spec.

## Expected behavior
Parsing succeeds for any valid JSON.
Parsing succeeds regardless of the HTTP path.

## Additional context
I ran into this issue using `gofetch` to test the implementation of tool filtering. Worth noting that this parsing mechanism works only on `Content-Type: application/json` and is not usable to parse JSON-RPC payloads generally as in the case of SSE response streams.

### PR DESCRIPTION
**Pull request by JAORMX**
## Summary

This PR fixes issue #1187 where the parsing middleware was failing on SSE streams when the path didn't contain \`/messages\`, \`/message\`, or \`/mcp\`.

## Problem

The MCP spec allows for various endpoints to be used:
- **Streamable HTTP transport**: single endpoint
- **SSE transport**: two distinct endpoints (one for SSE stream, one for messages)

However, our parsing middleware was only processing requests to specific paths, causing failures with MCP servers like gofetch that use different endpoint paths (e.g., \`/sse\` for both SSE stream and messages).

## Solution

- Removed the path restriction in \`shouldParseMCPRequest\` function
- Now parse all POST requests with JSON content type (except SSE establishment endpoints)
- The middleware is now path-agnostic and works with any valid MCP endpoint configuration

## Changes

1. **pkg/mcp/parser.go**: Updated \`shouldParseMCPRequest\` to remove path filtering
2. **pkg/mcp/parser_test.go**: Updated existing tests to reflect the new behavior
3. **pkg/mcp/parser_integration_test.go**: Added comprehensive integration tests using the mcp-go library

## Testing

- ✅ All existing tests pass
- ✅ Added integration tests with actual MCP server implementations
- ✅ Tested with various endpoint paths including:
  - Standard paths (\`/messages\`, \`/mcp\`)
  - Custom paths (\`/rpc\`, \`/api\`)
  - Tenant-specific paths (\`/tenant/123/messages\`)
  - Single endpoint configurations (like gofetch's \`/sse\`)

## Related Issues

Fixes #1187

## Checklist

- [x] Tests added/updated
- [x] All tests passing
- [x] Code follows project conventions
- [x] Integration tests added using mcp-go library

### CODE REVIEW

File: pkg/mcp/parser_integration_test.go [hunk 1]
```diff
@@ -0,0 +1,425 @@
...
+
+			if tc.transport == "sse" {
+				testServerURL = setupSSEServer(t, mcpServer, tc.ssePath, tc.messagePath, parsingCaptureMiddleware)
+				mcpClient, err = client.NewSSEMCPClient(testServerURL + tc.ssePath)
+			} else {
+				// For streamable HTTP, use a single endpoint
+				endpoint := "/mcp"
+				if tc.name == "Streamable HTTP with custom path" {
+					endpoint = "/api/v1/rpc"
+				}
```
Comment (blkt) [inline pkg/mcp/parser_integration_test.go]: **nit:** I noticed Cursor has the tendency to use `tc.name` to change the logic of the test.
I would change this to be a specific entry in the test case struct.

**Review by blkt — APPROVED** [review]
Very minor detail, let's merge this.

**Review by blkt — APPROVED** [review]
