### PR TITLE
Auto add remote server to clients

### LINKED ISSUE #1808: Remote MCP servers are not added or removed when you add or remove a client
## Bug description

I had one local and one remote MCP server set up in ToolHive. Then I registered a new client (Cursor). The local MCP was added to Cursor's config as expected, but the remote server was not. I ran `thv rm` and re-ran `thv run ...` for the remote server, and now it got added to Cursor.

Then I unregistered Cursor with `thv client remove cursor`. Again, the local server was cleaned up from Cursor's config as expected, but the remote server was left behind.

Seems `thv` just isn't accounting for remote servers when new clients are added or removed.

## Steps to reproduce

1. Have at least one local AND at least one remote MCP running in ToolHive.
2. Register a new client with `thv client setup` or `thv client register <client>`. Note the remote MCP is NOT added to the new client's config.
3. Run a new remote MCP server. Note it gets added to the new client, as expected.
4. Remove the client with `thv client remove <client>`. Note any remote MCP server(s) do NOT get removed from its config.

## Expected behavior

Remote MCP servers should get added or removed from client configs when clients are added or removed, just like local MCPs.

## Actual behavior

Remote servers are skipped in these operations.

## Environment (if relevant)
- OS/version: macOS, used Cursor as my example client
- ToolHive version: v0.2.17

### PR DESCRIPTION
**Pull request by amirejaz**
Remote servers were not being automatically added/removed from the clients when we register/remove client with/from Toolhive. Fixes #1808

### CODE REVIEW

File: pkg/client/manager.go [hunk 1]
```diff
@@ -205,6 +205,12 @@ func (m *defaultManager) RemoveServerFromClients(ctx context.Context, serverName
 	return nil
 }
 
+// shouldSkipWorkload determines if a workload should be skipped when adding/removing servers from clients.
+// Workloads are skipped if they are not MCP tool type and if they are not remote.
+func shouldSkipWorkload(workload core.Workload) bool {
+	return workload.ToolType != mcpToolType && !workload.Remote
```
Comment (eleftherias) [inline pkg/client/manager.go:211]: non-blocking: Is there a reason why toolType isn't set to MCP for remote servers?

Comment (amirejaz) [reply pkg/client/manager.go:211]: actually it is set to `remote`, do we have a strong opinion to set it to `mcp`?

Comment (eleftherias) [reply pkg/client/manager.go:211]: No strong opinion, maybe we should even get rid of `ToolType` because it's not really used anywhere. But that's a different topic.
