### PR TITLE
Default anonymous authentication

### LINKED ISSUE #2870: Registry controller does not initialize the server authentication
When we deploy any of the registry examples under `examples/operator/mcp-registries/` the server configuration lack the authorization field, so the server fails with the following error:

```
Error: failed to load configuration: invalid configuration: auth configuration is required
```

### PR DESCRIPTION
**Pull request by dmartinol**
Fix #2870

Adda a default anonymous authentication until the operator consistently manages this aspect.

### CODE REVIEW

**Comment by slyt3** [comment]
Hey, was reading through the code and spotted something weird.

You have this default config that sets auth to anonymous:
```go
config := Config{
    Auth: &AuthConfig{
        Mode: AuthModeAnonymous,
    },
}
```

But up in the AuthMode comments it says it defaults to oauth for "security-by-default". So there's a mismatch between what the docs say and what actually happens.

anyone who deploys this without thinking about auth config will be running wide open. 

Default to oauth and only go anonymous if someone explicitly sets it in the config? people have to consciously choose the insecure option instead of accidentally getting it.

Might be missing context on why its like this though

File: cmd/thv-operator/pkg/registryapi/config/config.go [hunk 1]
```diff
@@ -244,7 +261,12 @@ func (c *Config) ToConfigMapWithContentChecksum(mcpRegistry *mcpv1alpha1.MCPRegi
 const DefaultRegistryName = "default"
 
 func (cm *configManager) BuildConfig() (*Config, error) {
-	config := Config{}
+	config := Config{
+		// default to anonymous authentication until we model it consistently in the MCPRegistry CRD
+		Auth: &AuthConfig{
+			Mode: AuthModeAnonymous,
```
Comment (ChrisJBurns) [inline cmd/thv-operator/pkg/registryapi/config/config.go:267]: I think we should default to `oauth` and allow users to disable by specifying `anonymous`

Comment (dmartinol) [reply cmd/thv-operator/pkg/registryapi/config/config.go:267]: That's the plan. @jhrozek introduced auth config at the registry level so I'd expect there will an equivalent task to complete it in the operator (exposing the same settings).
This is just a fix to avoid the deployment error `auth configuration is required`.

**Comment by dmartinol** [comment]
> Thanks for doing this @dmartinol as it was getting tiring having to manually edit the config configmap. Although I think if we do add this change we'd need to enable it on the CRD too, because if we specify default of anonymous, we aren't giving users a way of providing oauth. So we should probably allow for the full auth config if we do have it in the operator

This reminds me of another issue I've found: if you `manually edit the config configmap` the operator should reconcile it back to the (errored) state, but this doesn't happen.

**Comment by dmartinol** [comment]
> Hey, was reading through the code and spotted something weird.
> 
> You have this default config that sets auth to anonymous:
> 
> ```go
> config := Config{
>     Auth: &AuthConfig{
>         Mode: AuthModeAnonymous,
>     },
> }
> ```
> 
> But up in the AuthMode comments it says it defaults to oauth for "security-by-default". So there's a mismatch between what the docs say and what actually happens.
> 
> anyone who deploys this without thinking about auth config will be running wide open.
> 
> Default to oauth and only go anonymous if someone explicitly sets it in the config? people have to consciously choose the insecure option instead of accidentally getting it.
> 
> Might be missing context on why its like this though

Hey @slyt3 , you are right: I copied only the minimal data types from the equivalent configuration types in the `toolhive-registry-server` project, to avoid managing the entire oidc stack.
As I replied before, I expect the feature will be completed to make it consistent with the server design, but this was not the goal of this PR.

TL;DR: I'm not forcing anyone to merge this PR, but without this fix the registry server won't start.

File: cmd/thv-operator/pkg/registryapi/config/config.go (hunk 1 above)
Comment (jhrozek) [reply cmd/thv-operator/pkg/registryapi/config/config.go:267]: you're right @dmartinol I should have thought about the operator from the start.

@ChrisJBurns @rdimitrov @dmartinol is the follow up tracked somewhere? Should I go and clean my mess or do you have that part planned?

Comment (rdimitrov) [reply cmd/thv-operator/pkg/registryapi/config/config.go:267]: Marking this as resolved so we can merge the PR
