### PR TITLE
Automatic type coercion for composite tool template expansion

### LINKED ISSUE #3113: Composite tools: Numeric parameters converted to strings during template expansion
## Description

When using composite tools with Go template syntax to pass numeric parameters, the values are converted to strings. Backend tools receive `"123"` instead of `123`, causing validation failures.

## Configuration That Breaks

```yaml
compositeTools:
  - name: "fetch_toolhive_issue"
    description: "Fetch a specific GitHub issue from the ToolHive repository"
    parameters:
      type: object
      properties:
        issue_number:
          type: integer
          description: "GitHub issue number to fetch"
        repo:
          type: string
          description: "Repository name"
          default: "toolhive"
      required:
        - issue_number
    steps:
      - id: "get_issue"
        tool: "github_issue_read"
        arguments:
          method: "get"
          owner: "stacklok"
          repo: '{{.params.repo}}'
          issue_number: '{{.params.issue_number}}'  # Gets converted to string
```

## Expected Behavior

`github_issue_read` should receive `issue_number` as an integer (`123`).

## Actual Behavior

`github_issue_read` receives `issue_number` as a string (`"123"`), causing validation to fail.

## Root Cause (Claude Code's Best Guess)

Template expansion in `pkg/vmcp/composer/template_expander.go:164` uses Go's `text/template` package, which always returns strings. When arguments are expanded at `pkg/vmcp/composer/workflow_engine.go:381`, numeric values become strings with no type recovery afterward.

## Proposed Solution

Apply type coercion after template expansion using the backend tool's InputSchema to recover correct types. The codebase already has this pattern for workflow outputs in `pkg/vmcp/composer/output_constructor.go` (lines 187-223) - extract and apply it to tool call arguments.

## Impact

Affects all composite tools using numeric or boolean parameters with template expansion (issue numbers, pagination, counts, ratios, flags, etc.).

### PR DESCRIPTION
**Pull request by jerm-dro**
# Summary

This PR fixes issue #3113 where numeric and boolean parameters in composite tools are converted to strings during Go template expansion, causing validation failures in backend tools.

### Problem

When composite tool workflows use template expansion (e.g., `{{.params.issue_number}}`), Go's `text/template` package always outputs strings. This means a parameter like `issue_number: 3113` becomes the string `"3113"` after expansion, causing backend tools to fail validation when they expect an integer.

### Solution

Introduced a new `pkg/vmcp/schema` package that provides automatic type coercion based on the backend tool's `InputSchema`. After template expansion, arguments are coerced back to their expected types (integer, number, boolean) before being sent to the backend.

We have some other logic for coercing outputs into the intended types. I attempted to refactor this, but there's enough differences (e.g. unmarshalling strings, default values) that sharing complicates the implementation. Given we don't need to touch the output code right now, I'll leave it as is for now with a note on eventually consolidating.

### Changes

**New Package: `pkg/vmcp/schema/`**
- `schema.go` - `TypeCoercer` interface and `MakeSchema()` factory
- `primitive.go` - Coercion for string/integer/number/boolean types
- `object.go` - Recursive coercion for nested objects 
- `array.go` - Coercion for typed array elements

**Key Design Decisions:**
- **Immutable value receivers** - Schema types use value receivers since they're immutable after creation
- **Passthrough for unknown schemas** - `MakeSchema()` always returns a valid `TypeCoercer`; callers don't need nil checks
- **Partial coercion** - If one property fails to coerce, others still succeed; failed values retain their original type
- **Single declarative test** - One table-driven test covers all coercion cases

**Modified:**
- `pkg/vmcp/composer/workflow_engine.go` - Integrates schema coercion after template expansion
- `test/integration/vmcp/helpers/backend.go` - `NewBackendToolWithSchema()` now accepts `mcp.ToolInputSchema` directly
- Extended VMCPSession to also store the Tools slice (with InputSchema) and include it when reconstructing capabilities for subsequent requests.

### Testing

- Unit tests in `pkg/vmcp/schema/schema_test.go` cover all primitive types, nested objects, arrays, and edge cases
- Integration tests in `test/integration/vmcp/vmcp_typing_integration_test.go` verify end-to-end coercion through composite tool workflows

### Example

```yaml
# Composite tool step with template expansion
steps:
  - id: get_issue
    tool: github_get_issue
    arguments:
      owner: "stacklok"
      repo: "toolhive"
      issue_number: "{{.params.issue_number}}"  # Expands to string "3113"
```

With this PR, if the backend tool's schema specifies `issue_number` as type `integer`, the string `"3113"` is automatically coerced to `int64(3113)` before the tool call.

Fixes #3113

### CODE REVIEW

File: pkg/vmcp/composer/workflow_engine.go [hunk 1]
```diff
@@ -386,6 +388,15 @@ func (e *workflowEngine) executeToolStep(
 		return expandErr
 	}
 
+	// Coerce expanded arguments to expected types based on backend tool schema.
+	// Template expansion returns strings, but backend tools expect typed values
+	// (integer, boolean, number) as defined in their InputSchema.
+	rawSchema := e.getToolInputSchema(ctx, step.Tool)
+	s := schema.MakeSchema(rawSchema)
+	if coerced, ok := s.TryCoerce(expandedArgs).(map[string]any); ok {
```
Comment (yrobla) [inline pkg/vmcp/composer/workflow_engine.go:396]: you could log failures when type coercion fails

File: pkg/vmcp/schema/primitive.go [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+}
+
+// makePrimitiveSchema creates a primitiveSchema from a raw JSON Schema map.
+func makePrimitiveSchema(raw map[string]any, schemaType string) primitiveSchema {
+	schema := primitiveSchema{
+		schemaType: schemaType,
+	}
+
+	if defaultVal, hasDefault := raw["default"]; hasDefault {
+		schema.defaultValue = defaultVal
```
Comment (yrobla) [inline pkg/vmcp/schema/primitive.go]: where is that used?

File: test/integration/vmcp/vmcp_typing_integration_test.go [hunk 3]
```diff
@@ -0,0 +1,231 @@
...
+					"str_param":  map[string]any{"type": "string"},
+					"int_param":  map[string]any{"type": "integer"},
+					"num_param":  map[string]any{"type": "number"},
+					"bool_param": map[string]any{"type": "boolean"},
+				},
+				Required: []string{"str_param", "int_param", "num_param", "bool_param"},
+			},
+			func(_ context.Context, args map[string]any) string {
+				receivedArgs = args
+				result, _ := json.Marshal(args)
```
Comment (yrobla) [inline test/integration/vmcp/vmcp_typing_integration_test.go]: shall we error when json fails?

File: pkg/vmcp/schema/primitive.go [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+		}
+
+	case "number":
+		if v, err := strconv.ParseFloat(str, 64); err == nil {
+			return v
+		}
+
+	case "boolean":
+		switch str {
+		case "true", "True", "TRUE", "1":
```
Comment (yrobla) [inline pkg/vmcp/schema/primitive.go]: there is a ParseBool method from strconv, why not use it

**Review by yrobla — COMMENTED** [review]
added some comments

File: pkg/vmcp/schema/primitive.go (hunk 2 above)
Comment (jerm-dro) [reply pkg/vmcp/schema/primitive.go]: I deleted this for now.

File: pkg/vmcp/schema/primitive.go (hunk 4 above)
Comment (jerm-dro) [reply pkg/vmcp/schema/primitive.go]: Nice. I updated the output code to do the same to avoid inconsistencies
