### PR TITLE
fix: Cannot deploy MCPRegistry from git in OpenShift

### LINKED ISSUE #2250: Cannot deploy MCPRegistry from git in OpenShift
Fetch of registry data fails in OpenShift when the data source is pulled from git.

Registry spec:
```yaml
spec:
  displayName: thv-registry
  enforceServers: false
  source:
    format: toolhive
    git:
      branch: main
      path: pkg/registry/data/registry.json
      repository: https://github.com/stacklok/toolhive
    type: git
  syncPolicy:
    interval: 5m
```

Error in registry status
```
status:
  apiStatus:
    message: Registry API deployment is not ready yet
    phase: Deploying
  conditions:
  - lastTransitionTime: "2025-10-17T18:28:37Z"
    message: 'Fetch failed: failed to create temporary directory: mkdir /tmp/mcpregistry-git-1447472569:
      read-only file system'
    reason: FetchFailed
    status: "False"
    type: SyncSuccessful
```

### PR DESCRIPTION
**Pull request by dmartinol**
Fixes #2250 
## Root cause
- /tmp is not writable and the clone fails
- Also, even after mounting an emptyDir to the deployment, the clone requires large memory that may exceed the limits causing the controller restart
- Clone was performed twice because the FetchRegistry also called CurrentHash which runs another clone

## Proposed solution
~- Using sparse checkout to reduce the local repo size:~
~  - Note: this also copies the other files and the subfloders from the registry data folder~
- Use in-memory FS (thanks @JAORMX and @jhrozek ) for the suggestion
- Do not clone again the repo to compute the hash
- Added GC options in deployment to expedite the execution of the Go Garbage Collector

## Alternatives
- If the memory usage remains too high, we can use a direct HTTP raw fetch of the file with no storage and no git protocol
  -  The raw URL depends on the Git provider and requires custom implementation. Some providers or versions may not be supported.
- Connect a PVC with some storage area
  - Caching and reuse of existing local repos would improve performance (git fetch instead of full clone)

### CODE REVIEW

File: cmd/thv-operator/pkg/git/integration_test.go [hunk 1]
```diff
@@ -39,7 +41,7 @@ func TestDefaultGitClient_FullWorkflow(t *testing.T) {
 	// Create a test file
 	testFilePath := filepath.Join(sourceRepoDir, "registry.json")
 	testContent := `{"name": "test-registry", "version": "1.0.0"}`
-	err = os.WriteFile(testFilePath, []byte(testContent), 0644)
+	err = os.WriteFile(testFilePath, []byte(testContent), 0600)
```
[the remark this answers is not in the document]
Comment (JAORMX) [reply cmd/thv-operator/pkg/git/integration_test.go]: no, bad bot!

**Comment by JAORMX** [comment]
@claude can you review this with a focus on security?

File: cmd/thv-operator/pkg/git/client.go [hunk 2]
```diff
@@ -29,132 +27,220 @@ func NewDefaultGitClient() *DefaultGitClient {
...
+func (c *DefaultGitClient) FetchFileSparse(ctx context.Context, config *CloneConfig, filePath string) ([]byte, error) {
+	logger := log.FromContext(ctx)
+
+	// Log memory stats before operation
+	var memBefore runtime.MemStats
+	runtime.ReadMemStats(&memBefore)
+	logger.V(1).Info("Git operation starting",
+		"url", config.URL,
+		"file", filePath,
+		"alloc_mb", memBefore.Alloc/(1024*1024))
```
Comment (JAORMX) [inline cmd/thv-operator/pkg/git/client.go]: Let's make this `1024*1024` a constant.

File: cmd/thv-operator/pkg/git/client.go [hunk 3]
```diff
@@ -29,132 +27,220 @@ func NewDefaultGitClient() *DefaultGitClient {
...
+	defer func() {
+		logger.V(1).Info("Git cleanup starting")
+
+		// Explicitly clear repository reference to help GC
+		if repoRef != nil && *repoRef != nil {
+			*repoRef = nil
+		}
+
+		// Force garbage collection to release memory
+		runtime.GC()
```
Comment (jhrozek) [inline cmd/thv-operator/pkg/git/client.go]: Umm this kinda triggers my spider sense..

At this point, wouldn't it be better to use `github.com/go-git/go-billy/v5/memfs` and `github.com/go-git/go-git/v5/storage/memory` ? This would allow us to avoid using the /workspace mount, would clean the clone automatically with normal GC, avoiding the manual GC invocation etc.

Claude says this migth do the trick (unverified):
```go
  const (
      MaxMemFSSize    = 50 * 1024 * 1024  // 50MB
      MaxCloneTimeout = 2 * time.Minute
  )

  // FetchFileSparse with full DoS protection
  func (c *DefaultGitClient) FetchFileSparse(ctx context.Context, config *CloneConfig, filePath string) ([]byte, error) {
      logger := log.FromContext(ctx)

      // 1. Validate URL (prevent malicious URLs)
      if err := validateGitURL(config.URL); err != nil {
          return nil, fmt.Errorf("invalid git URL: %w", err)
      }

      // 2. Enforce timeout
      _, hasDeadline := ctx.Deadline()
      if !hasDeadline {
          var cancel context.CancelFunc
          ctx, cancel = context.WithTimeout(ctx, MaxCloneTimeout)
          defer cancel()
      }

      // 3. Size-limited memfs
      fs := newSizedMemFS(MaxMemFSSize)
      storer := memory.NewStorage()

      // 4. Minimal clone options
      cloneOptions := &git.CloneOptions{
          URL:          config.URL,
          Depth:        1,              // Shallow
          SingleBranch: true,           // One branch only
          Tags:         git.NoTags,     // No tags
          NoCheckout:   true,           // Don't checkout yet
      }

      if config.Branch != "" {
          cloneOptions.ReferenceName = plumbing.NewBranchReferenceName(config.Branch)
      } else if config.Tag != "" {
          cloneOptions.ReferenceName = plumbing.NewTagReferenceName(config.Tag)
      } else if config.Commit != "" {
          // REJECT commit-based clones (too dangerous)
          return nil, fmt.Errorf("commit-based cloning disabled for security reasons; use branch or tag")
      }

      // 5. Clone with all protections
      repo, err := git.CloneContext(ctx, storer, fs, cloneOptions)
      if err != nil {
          if strings.Contains(err.Error(), "size limit exceeded") {
              return nil, fmt.Errorf("repository exceeds 50MB limit")
          }
          return nil, fmt.Errorf("clone failed: %w", err)
      }

      // 6. Sparse checkout and read file
      if err := c.performSparseCheckout(repo, filePath); err != nil {
          return nil, err
      }

      content, err := c.readFileFromMemFS(fs, filePath)
      if err != nil {
          return nil, err
      }

      logger.Info("Fetch completed",
          "url", config.URL,
          "file", filePath,
          "size_kb", len(content)/1024,
          "memfs_size_kb", fs.CurrentSize()/1024)

      return content, nil
  }
```

Comment (dmartinol) [reply cmd/thv-operator/pkg/git/client.go]: I forgot to update the thread: I'm working on this review, as proposed by @JAORMX on Discord.
And not using the sparse clone which seems to make things more complex and may not be fully supported by all git providers. Moving the PR to draft until it is validated.
Thanks!

File: deploy/charts/operator/templates/deployment.yaml [hunk 4]
```diff
@@ -64,6 +68,8 @@ spec:
             value: "{{ .Values.operator.proxyHost }}"
           - name: TOOLHIVE_REGISTRY_API_IMAGE
             value: "{{ .Values.registryAPI.image }}"
+          - name: WORKSPACE_DIR
+            value: "/workspace"
```
Comment (jhrozek) [inline deploy/charts/operator/templates/deployment.yaml]: This is not needed anymore and a dead YAML code now, right?

File: cmd/thv-operator/pkg/git/client.go [hunk 5]
```diff
@@ -49,16 +54,37 @@ func (c *DefaultGitClient) Clone(ctx context.Context, config *CloneConfig) (*Rep
...
+	storerFs := memfs.New()
+	storerFs = &LimitedFs{
+		Fs:            storerFs,
+		MaxFiles:      10 * 1000,
+		TotalFileSize: 100 * 1024 * 1024,
+	}
+	storerCache := cache.NewObjectLRUDefault()
+	storer := filesystem.NewStorage(storerFs, storerCache)
+
+	repo, err := git.Clone(storer, memFS, cloneOptions)
```
Comment (jhrozek) [inline cmd/thv-operator/pkg/git/client.go]: We went from `git.PlainCloneContext` to `git.Clone` (no context), could we use `git.CloneContext` ?

File: cmd/thv-operator/pkg/git/client.go [hunk 6]
```diff
@@ -125,19 +151,39 @@ func (*DefaultGitClient) GetFileContent(repoInfo *RepositoryInfo, path string) (
...
+		_ = util.RemoveAll(repoInfo.storerFilesystem, "/")
+	}
+
+	// 4. Nil out all references
+	repoInfo.objectCache = nil
+	repoInfo.storerFilesystem = nil
+	repoInfo.Repository = nil
+
+	// 5. Force GC to reclaim memory
+	runtime.GC()
```
Comment (jhrozek) [inline cmd/thv-operator/pkg/git/client.go:185]: I still don't think nudging the GC is necessary.

File: deploy/charts/operator/templates/deployment.yaml [hunk 7]
```diff
@@ -43,6 +43,10 @@ spec:
           ports:
             {{- toYaml .Values.operator.ports | nindent 12 }}
           env:
+          - name: GOMEMLIMIT
+            value: 300MiB # Explicit limit (update as needed: keep it close to memory limits)
```
Comment (jhrozek) [inline deploy/charts/operator/templates/deployment.yaml]: This is bigger than the default limits (but within openshift limits)

**Review by jhrozek — COMMENTED** [review]
Much better! A couple of findings inline

File: deploy/charts/operator/templates/deployment.yaml (hunk 7 above)
Comment (dmartinol) [reply deploy/charts/operator/templates/deployment.yaml]: I will add chart values to make this explicit, otherwise it can't be calculated here.

File: cmd/thv-operator/pkg/git/client.go (hunk 6 above)
Comment (dmartinol) [reply cmd/thv-operator/pkg/git/client.go:185]: Testing it

Comment (dmartinol) [reply cmd/thv-operator/pkg/git/client.go:185]: Without this call, the Pod still crashes with OOMKilled error.
Looks like it's really needed.
I would postpone this finalization once the logic moves to the thv-registry-api, since the same issue will be there, WDYT?

File: cmd/thv-operator/pkg/git/client.go (hunk 5 above)
Comment (dmartinol) [reply cmd/thv-operator/pkg/git/client.go]: updated

File: cmd/thv-operator/pkg/git/client.go (hunk 6 above)
Comment (jhrozek) [reply cmd/thv-operator/pkg/git/client.go:185]: yeah, good call.
